sudo: required
services:
- docker
before_install:
- docker pull euforia/fpm
install:
- true
script:
- ./scripts/build.sh
- ls -l ./build
before_deploy:
- rvm use default
deploy:
- provider: script
  skip_cleanup: true
  script: ./scripts/push-packages.sh
  on:
    branch: master
env:
  global:
    secure: tumDxwY+Lb19rKshHGX2tMpO30yZKrsEegzIRTaPx0kszGMiCoGwnuBr7alAwN7Nf1ve2W+j+jdDMb+oKVJFTlw+yGz4DpCygM1npz3pXRP8OJycXXe/1hZxSx1pgDn/OFIsQG1o+5+iPqMH2LY/0EKYcUN+XRI7i/L/ed7lzxy/Ex5ocx2SOO5s3e21OcIl8UtqGJqYoWFNQU8mVC72cgJ9/SvkaNOEI/F62o9r2sAuRL/f7o2l/XdOKjiPf2eyImwxBFY/Kgcnkfrvw40HZ8kWWVas8CKJF0gX+YNXMC71GzKVI5aMai4jyeY0Xtvl5o1zUvEs4QiNmvbfOtCKE3z8iibxwj9FxWXC2gZLrqJw1DqJWBsw7tkgdrQ2NmvML/1TneKEtTCdVG3GI2ayYRiTXQ+3KokeKXW3O9JcUKm8u1gc5fKDHBl5NYNuZMXMdB61i4kGIaMyQ065CftE3g1LH7OpRszIL9JLTE0L4V6hF/Y/CRDage7ez7NyWM93PzRHfUfMoVlRNJ8w2hrXdFGS8OpuPuspvHjSxtWaLuzCkriHy79dcjbwVZaNPtS9bagR+vOwLm4uWQVcwttKepMgeC+It1SVGDhyjiBtMH10JsAS3YmaO6Fv8U5kJytU9E/sMxyqalpm8UAxo7AJ11dpiPh/40EN/5Xt8fJyhsQ=
notifications:
  slack:
    on_start: always
    on_success: always
    on_failure: always
    secure: Hfw9ZzzDwBWeP4BmReo7OxW3THj2Yr+HZb1t8Xnp290ZkWxmWAb4OuzuuBW9js6IKHDKozv0kUygOUtfC2mKB9OtDTzulEjIE2vfWXcMq4dvhf3MiwDeB+SJd8cM5H0qreTkuMD2PxfteUQyp+0Uy7IftBV8kf44UPkOi98TozYpmPBF5KTmCaQuQjXEONaHENYQ6xuIX2RXCK4ENPCNUulJQsfhocDOnA3oVUPnkeFyN2WjxOIoWagTMr4nnkl72z04/f2QTKejITQ0qchGKssHsb4IdJuZFPoMXqLiPgyc22IVvMmQ9zWstPuFDgcKE0kBa1l1UwsqxMwDhAfaN3zdDPC2i7zIShCfgfy+etUvQf9u3lFCVNPJecBpqUbbDRFY+XoaClDVYxDhyzx/+7ZqTAwtBs1ku8tLOK7F/YakqfKYF4LAgmtTZ5eyF4gO59y1xbjJKDvDOg+puUE+Q0PXU2WJcmEcIdwZLyuya/w5gWcZeLl52rvQqzNL/408EAbpFrDI1TFK0WrLXABSKC45uwIv4Tachf674gW2vLFgX0vPq9+i17LUjLEdGD290mHgisZ7VZ/V/+l7VCOmU/V9pGoCwT1aMRmXe8z3o8qW6qR7RLhypzf5o62gHZtvFbgcE3JPEk3vb2jHTO9nvukhadZcgvZzQ+huUKZ86zk=
